/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.34).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package co.com.cloud.computing.msbacklog.api;

import co.com.cloud.computing.msbacklog.model.Backlog;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen",
        date = "2022-05-23T04:04:15.496Z[GMT]")
@Validated
public interface BacklogsApi {

    @Operation(summary = "Retorna HTTP 201 al crear exitosamente.", description = "Adicionar nuevo bakclog.", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Creado Exitasamente", content =
        @Content(mediaType = "application/json", schema = @Schema(implementation = Backlog.class))),
        
        @ApiResponse(responseCode = "400", description = "Bad Request") })
    @RequestMapping(value = "/backlogs",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Backlog> backlogsPost(@Parameter(in = ParameterIn.DEFAULT,
            description = "Cuerpo de la petición Backlogs", required=true, schema=@Schema())
                                         @Valid @RequestBody Backlog body);

}

